### ISSUE TITLE
Give an error if we can't connect to the database

### ISSUE THREAD

**Issue by pmer** [savetheinternet/Tinyboard#10]
**ISSUE**

If we can't connect to the database, we tell all users that we think they are bots. 

**REPRODUCTION**

When the database connection parameters are setup incorrectly:
- Make a post.

**EXPECTED RESULT**

An error message will be shown describing the actual situation.

**Comment by pmer** [comment]
We do have test.php to tell us if there is anything wrong with the database, but in our readme we recommend that users delete it.

Also, telling everyone that they are a bot is not truthful about the problem at hand.

**Comment by savetheinternet** [comment]
Who's to say they aren't bots?

I'll have a look at it later.

**Comment by pmer** [comment]
I hope you're kidding.

**Comment by savetheinternet** [comment]
I was, but not about having a look at it later.

Sorry, I'm a little busy right now.

**Comment by savetheinternet** [comment]
On a database misconfiguration, a "Database error." error is shown.

Perhaps this was a "ROOT" misconfiguration. That would make more sense.
