### ISSUE TITLE
Per-Boards Configs

### ISSUE THREAD

**Issue by rdfcp1** [savetheinternet/Tinyboard#100]
Hi, this is my first time here !

I made my own imageboard with Tinyboard recently. I'm really happy with this service.
 I'm a beginner et coding but I'm proud of myself for what I've already done.

I just wanted to know if there's a simple way to make per-boards configs. I explain : If I want, for exemple, to make a board with a board with a force_body_op=true and another with a force_body_op=false. How could I easily do that ?

Thanks in advance !

**Comment by russelg** [comment]
You can put a config.php file in the board's directory and those values will override the specified configs.

**Comment by rdfcp1** [comment]
Thank you very much !
