### ISSUE TITLE
Creating a textboard

### ISSUE THREAD

**Issue by rdfcp1** [savetheinternet/Tinyboard#103]
I plan to create a Textboard on my imageboard, but I haven't found a way to do that properly.
The only way I found was to delete the "No image" error from the post.php for the specified board. Unfortunately now I can't rebuild thread pages..

Has anyone ever made that ? What should I do ?

**Comment by savetheinternet** [comment]
Tinyboard does not currently support textboards, sorry.

**Comment by rdfcp1** [comment]
Thank you very much ! :)
