### ISSUE TITLE
No support for SVG and other image formats.

### ISSUE THREAD

**Issue by savetheinternet** [savetheinternet/Tinyboard#11]
In the future, Tinyboard should support as many image formats as possible.

Note: This issue is specifically for SVG formats.

**Comment by ghost** [comment]
To support SVG, you just need to set the header to something like this:

header("Content-type: image/svg+xml");

And then echo out shit. You can, of course, link to SVG documents (might need to add MIME types, though). And you can embed using something like this:

http://pastebay.com/118321

That only works on XHTML documents though, iirc.

**Comment by savetheinternet** [comment]
Done with ImageMagick in ab0d6e27d77b868c33dde7098d984f60dce9995c.
