### ISSUE TITLE
recaptcha_public field missing

### ISSUE THREAD

**Issue by GIANTCRAB** [savetheinternet/Tinyboard#111]
![untitled](https://f.cloud.github.com/assets/1075708/648428/ed230c0a-d42a-11e2-8615-e3f7e26c5f58.png)
The reCaptcha public field seems to be missing.
Any ideas why?

I'm running the latest PHP version, 5.4.16, lighttpd, fastcgi, mysql.
Viewing on Opera 12.15 1748 build, Windows 7 64bit.
Downloaded from https://github.com/savetheinternet/Tinyboard/archive/master.tar.gz on 13/6/2013 GMT+0800

**Comment by GIANTCRAB** [comment]
Never mind, I've edited the instance-config.php instead.

**Comment by savetheinternet** [comment]
The web config editor is a bit of a mess. It works by simply (well, in reality it is far from simple) parsing the lines of code in inc/config.php, extracting the variables and default values. When you submit changes, it edits your instance-config.php and puts them at the end.

I highly recommend editing instance-config.php directly if you know how to. The web config editor is for those who don't understand even the basics of reading/writing PHP code.

Nevertheless, this appears to be a legitimate bug. And I will fix it in due time.
