### ISSUE TITLE
DB table prefix

### ISSUE THREAD

**Issue by mitsukarenai** [savetheinternet/Tinyboard#118]
[improvement]

/inc/config.php
`$config['db']['prefix'] = 'tinyboard_';`
(add variable whenever necessary for SQL queries)

Reason: many shared hosting allow only 1 MySQL database, meaning if admin has more than one Tinyboard (or any other CMS using same table names), it can be pretty messed up.

This should allow admin to set a prefix for the given Tinyboard, like "tinyboard5_", resulting in the following tables being used:

```
tinyboard5_antispam
tinyboard5_bans
tinyboard5_boards
...
```

**Comment by savetheinternet** [comment]
I've wanted to do this for a long time, but it requires a _lot_ of changes to the code.

**Comment by czaks** [comment]
Some preprocessing for queries before executing may make it easier, still it would be harder to handle all the corner cases with JOINs, multiple tables selections, embedded queries, etc. While doing a full SQL parser for that to work is not an option, I still believe, that some clever regular expression might make it work.

**Comment by savetheinternet** [comment]
@czaks 

I think because of the complexity of some of Tinyboard's SQL queries, building a regular expression may not be a viable solution. Perhaps we could go and replace every `query()` and `prepare()` call with something like:

``` php
query('SELECT * FROM ``posts_b``');
```

(Note the double-backtick.)

And then a regular expression in `query()` and `prepare()`:

``` php
function query($query) {
    $query = preg_replace('/``(.+)``/', $config['db']['prefix'] . '$1', $query);
    // ...
}
```
