### ISSUE TITLE
Shouldn't bother resizing and redrawing image when it's already below the minimum.

### ISSUE THREAD

**Issue by savetheinternet** [savetheinternet/Tinyboard#12]
When a thumbnailed image is going to be the same (in dimension), just copy the entire file and use that as a thumbnail instead.

**Comment by ghost** [comment]
Just check the width and height, and if it's equal to or less than a pre-determined amount, use that instead of a thumbnail. I can whip up some sample code if you want.

**Comment by savetheinternet** [comment]
Completed in 5f94009fad79ec2babaadb8e16e6f83f163d2964.
