### ISSUE TITLE
Outputting thread subject in header/title

### ISSUE THREAD

**Issue by ghost** [savetheinternet/Tinyboard#122]
Attempting to pinpoint how to output the subject of the thread currently being viewed as a header:title element of the html.  Can this be done?

**Comment by captainspazz** [comment]
I'd like this too

**Comment by russelg** [comment]
It's done with 4chan X, so of course it's possible.

**Comment by russelg** [comment]
Here is what the official 4chan extension has:

``` javascript
Main.setTitle = function() {
  var title, entities;

  if (!(title = $.cls('subject', $.id('pi' + Main.tid))[0].textContent)) {
    if (title = $.id('m' + Main.tid).innerHTML) {
      entities = document.createElement('span');
      entities.innerHTML = title.replace(/<br>/g, ' ');
      title = entities.textContent.slice(0, 50);
    }
    else {
      title = 'No.' + Main.tid;
    }
  }

  document.title = '/' + Main.board + '/ - ' + title;
};
```

It wouldn't be too hard to adapt this for tinyboard.

**Comment by ghost** [comment]
Through the template itself, though, and not via javascript, since titles done in this way (javascript) wouldn't show up properly in search engines, would they?

**Comment by savetheinternet** [comment]
Yes, you should be able to do this without Javascript. I will work on it now.

**Comment by savetheinternet** [comment]
This can now be done with

``` php
$config['thread_subject_in_title'] = true;
```
