### ISSUE TITLE
i18nized until() and ago() functions broken with gettext.php (ngettext)

### ISSUE THREAD

**Issue by savetheinternet** [savetheinternet/Tinyboard#125]
I believe this problem only appears when the PHP `gettext` extension isn't installed. The pure-PHP gettext library I included as a fallback (`inc/lib/gettext`) is not perfect.

>  Notice: Use of undefined constant INTEGER - assumed 'INTEGER' in inc/lib/gettext/gettext.php(361) : eval()'d code on line 
> 
>  Notice: Use of undefined constant EXPRESSION - assumed 'EXPRESSION' in inc/lib/gettext/gettext.php(361) : eval()'d code on line 1
> 
> Notice: Undefined index: EXPRESSION in inc/lib/gettext/gettext.php on line 396

I'm not sure whether the problem arises from the gettext library itself or from @czaks's implementation of `ngettext` in babeec8bb9f54eece943b74628c95f976f5ee814.

``` php
$config['locale'] = 'pl_PL.UTF-8'; // Errors appear
$config['locale'] = 'en'; // No problems
```

![Screenshot](http://i.imgur.com/DEWab8Y.png)

**Comment by czak** [comment]
It's @czaks not @czak :)

**Comment by savetheinternet** [comment]
What's the difference? Fix it, buddy.

**Comment by savetheinternet** [comment]
I used the Polish plural form from [here](http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html) in my fix.
