### ISSUE TITLE
Just an idea I had

### ISSUE THREAD

**Issue by infamousbutterly** [savetheinternet/Tinyboard#127]
A nice feature would be access to the instance-config.php file from the moderation panel. I imagine it wouldn't be too hard to add a web based code editor for it. Not urgent, but it would be pretty damn convenient.

**Comment by savetheinternet** [comment]
`mod.php?/config` already exists for this. I don't recommend using it.

![Screenshot](http://i.imgur.com/uZHEL9S.png)

Or did you mean an actual file editor so you can edit `inc/instance-config.php` manually through the mod panel?

**Comment by infamousbutterly** [comment]
Yes, I did mean an actual file editor. You can only edit a select few things through the config editor.
