### ISSUE TITLE
After latest update, this happens when I try to do a post search.

### ISSUE THREAD

**Issue by infamousbutterly** [savetheinternet/Tinyboard#128]
Warning: Cannot modify header information - headers already sent by (output started at /home3/pollina2/public_html/aevus/inc/config.php:2) in /home3/pollina2/public_html/aevus/inc/mod/pages.php on line 185
![screenshot_19](https://f.cloud.github.com/assets/4838691/898241/5be28680-fb08-11e2-87e0-21c1585944d2.png)

**Comment by savetheinternet** [comment]
Are you sure your `inc/config.php` file is unedited? Do a `git checkout inc/config.php`.

**Comment by infamousbutterly** [comment]
I only edited it once, and that was just to add the new lines in from the last commit. Should I try and just do a full re-install? Also, how does on execute that command on a hosted server?

**Comment by savetheinternet** [comment]
OK, I assumed you were using git. Please check at the top of your `inc/config.php` file and remove any whitespace before or above `<?php`.

**Comment by infamousbutterly** [comment]
No, that didn't work. There was white space however. Could it be my host?

**Comment by savetheinternet** [comment]
I'm not sure what it is, but it is not a Tinyboard bug. Sorry, I can't help you.
