### ISSUE TITLE
Little revision of javascripts

### ISSUE THREAD

**Issue by glooom** [savetheinternet/Tinyboard#134]
Is it possible to show links to replies in the OP-post? And to enable preview of the OP-post, when the link to it in the reply is pointed with the mouse? It would be really cool, because the "(OP)"-sign near the link to OP-post looks ridiculous. Thanks.

**Comment by czaks** [comment]
OP preview works in vichan-devel branch

**Comment by glooom** [comment]
vichan-devel version of post-hover.js crashed both of my browsers - opera and firefox. not an option, LOL :)

**Comment by czaks** [comment]
Be aware that vichan-devel's post preview is dependent on the ukko (overboard) patchset (because it supports interboard linking and there's an issue with duplicate post ids). It is not compatible with vanilla tinyboard. At least until STI merges the rest.
