### ISSUE TITLE
Query empty 

### ISSUE THREAD

**Issue by infamousbutterly** [savetheinternet/Tinyboard#135]
When you enable or rebuild the cache for the recent posts theme it gives you a query empty error.

**Comment by savetheinternet** [comment]
Do you have any boards (minus those configured to be excluded from the theme)?

No boards = empty query.

**Comment by infamousbutterly** [comment]
I did, but I noticed on my ftp server it had failed to transfer one of the files for the recent theme, so I'm certain that's what caused it. It's all working now.
