### ISSUE TITLE
News.html problem

### ISSUE THREAD

**Issue by samip5** [savetheinternet/Tinyboard#137]
Hello,

When i try to edit templates/themes/categories/news.html it wont show up in the correct page which is index.html (I think.) so how can i add this to it?

<code>

``` html
    <article>
      <h4 id="id1">
       <a class="permalink" href="#id1">#</a> <span class="newssub">New /777/! (Fixed)  by  Found   - 08/18/13 @ 12:42 PM EEST  </span>
      </h4>

    <p>
        Greetings everybody using this site. I whoud like to get info what should i do with the Flood thing cuz i have no idea about fixing it now...
       </p>
    </article>
```

**Comment by sad** [comment]
If you wish to add a news entry, just install the "Basic" template, and click 'News' under 'Messages' in mod.php.
You needn't add entries manually.

![snapshot](https://f.cloud.github.com/assets/2056111/982498/c3aff002-07f8-11e3-9012-2cd8b3c726bf.png)

**Comment by samip5** [comment]
Okey thanks for the info. What about getting tabs on that page with Rules?

Also i'm currently using the categories sidabar as default homepage so any ideas to get an rules tab too?

Like this:

![like-this](https://f.cloud.github.com/assets/1703002/982563/b07045d6-0803-11e3-8be2-d4ff0c225645.JPG)

**Comment by savetheinternet** [comment]
As this isn't really an issue, I'm going to redirect you to [here](http://tinyboard.org/demo/mod.php?/sup/index.html).
