### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sad** [savetheinternet/Tinyboard#138]
I'm trying to run install.php, and am getting this. I'm using a VPS with PHP 5.3.10-1ubuntu3.6, and LAMP Stack installed.

Fatal error: Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/var/www/templates/cache/cf/ed).' in /var/www/inc/lib/Twig/Environment.php:1206 Stack trace: #0 /var/www/inc/lib/Twig/Environment.php(323): Twig_Environment->writeCacheFile('/var/www/templa...', 'loadTemplate('page.html') #2 /var/www/inc/template.php(61): Twig_Environment->render('page.html', Array) #3 /var/www/install.php(408): Element('page.html', Array) #4 {main} thrown in /var/www/inc/lib/Twig/Environment.php on line 1206 Fatal error: Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/var/www/templates/cache/d9/bc).' in /var/www/inc/lib/Twig/Environment.php:1206 Stack trace: #0 /var/www/inc/lib/Twig/Environment.php(323): Twig_Environment->writeCacheFile('/var/www/templa...', 'loadTemplate('error.html') #2 /var/www/inc/template.php(61): Twig_Environment->render('error.html', Array) #3 /var/www/inc/display.php(101): Element('error.html', Array) #4 /var/www/inc/functions.php(226): error('Caught fatal er...', 3) #5 [internal function]: fatal_error_handler() #6 {main} thrown in /var/www/inc/lib/Twig/Environment.php on line 1206

**Comment by savetheinternet** [comment]
Give PHP permission to write to `/var/www/templates`.

I'll add this to the pre-installation test page.

**Comment by sad** [comment]
All done! Thanks :smile:

**Comment by savetheinternet** [comment]
5cc7bd860fe653db831b20c7937a80ef35221f56.
