### ISSUE TITLE
Install.php issues.

### ISSUE THREAD

**Issue by NukeFace8** [savetheinternet/Tinyboard#139]
When I get to the Installation Complete section I get errors.

The errors encountered were:

Duplicate entry 'b' for key 1
Duplicate entry '1' for key 1
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1' at line 33

Then when I click ignore errors and complete installation, then I get another error.

Error
An error has occured.
Table 'tinyboardsql.posts_b' doesn't exist

Any ideas? Thanks, Matt.

**Comment by czaks** [comment]
What is your mysql version?

**Comment by NukeFace8** [comment]
MySQL Version:
5.0.91-log

**Comment by savetheinternet** [comment]
Likely a Tinyboard bug, but upgrading your MySQL server to something decent will probably fix it for now.

**Comment by NukeFace8** [comment]
I had an older version of TinyBoard working before, my website is hosted off of domain.com, so I am assuming I cannot update MySQL, they do that themselves.

**Comment by savetheinternet** [comment]
Oh, shit. Sorry, this a bug I introduced yesterday. Nothing to do with the database version.

[Fixed.](/savetheinternet/Tinyboard/commit/0bb254fdb37990958b17c1c72b59f747eab2e3f0)
