### ISSUE TITLE
MySQL error. Prat 2

### ISSUE THREAD

**Issue by glooom** [savetheinternet/Tinyboard#140]
Hi. New version of Tinyboard (downloaded 5 minutes ago) shows an error: 

"SQL errors were encountered when trying to install the database. This may be the result of using a database which is already occupied with a Tinyboard installation; if so, you can probably ignore this". The errors encountered were:
BLOB/TEXT column 'filehash' used in key specification without a key length.
Ignore errors and complete installation".

I ignored the error and on the next screen got: "Table 'newchan.posts_b' doesn't exist". 

I am using MySQL version 5.5.32.  And to make it clear: my database was not "occupied with a Tinyboard" - it was new. Looks like this case is related to old issue: http://github.com/savetheinternet/Tinyboard/issues/136  Can I do something with it? Thanks.

**Comment by savetheinternet** [comment]
Sorry, please pull the latest revision. This bug was introduced yesterday and fixed just now.
