### ISSUE TITLE
Your post looks automated.

### ISSUE THREAD

**Issue by sithtoast** [savetheinternet/Tinyboard#142]
Heyo, 
So I have shared my board with people on campus and for some reason I can post (i'm guessing since i'm a mod and all) and others cannot and are met with the automated error message.

My current settings are as follows:

spam hidden_inputs_min = 4
spam hidden_inputs_max = 12
spam hidden_inputs_max_pass = 12
spam hidden_inputs_expire = 10800

**Comment by savetheinternet** [comment]
`$config['spam']['unicode'] = false;`

Does this fix it?

**Comment by savetheinternet** [comment]
(You will need to rebuild after making any changes to $config['spam'].)

**Comment by sithtoast** [comment]
It looks like it. Though my users are getting the chan_time SQL error again.

**Comment by savetheinternet** [comment]
If you pulled the latest commit, the chan_time SQL error is gone.

**Comment by sithtoast** [comment]
lol i gotta pull :)

**Comment by sithtoast** [comment]
Awesome! Everything works!

**Comment by savetheinternet** [comment]
To confirm, did `$config['spam']['unicode'] = false;` fix it? Can I have a link to your site?
