### ISSUE TITLE
The catalog link from inside a thread incorrectly links to <board>/res/catalog.html

### ISSUE THREAD

**Issue by forbjok** [savetheinternet/Tinyboard#143]
When browsing a thread (as opposed to browsing the board itself), the catalog link incorrectly links to "<board>/res/catalog.html" instead of "<board>/catalog.html", resulting in a 404 when the link is clicked.

**Comment by savetheinternet** [comment]
No, it doesn't. Use `$config['catalog_link']`.

**Comment by forbjok** [comment]
What is that setting supposed to do?
I tried settng it to something, but it didn't seem to affect the catalog link, and as far as I can tell that variable isn't referenced anywhere in the code.

**Comment by seisatsu** [comment]
Use `$config['catalog_link'] = 'catalog.html';`
If you are using catalog-link.js, disable it. It's an older and broken system for doing the same thing.
