### ISSUE TITLE
How to make categories?!

### ISSUE THREAD

**Issue by azat-io** [savetheinternet/Tinyboard#149]
"Prerequisites not met!
This theme requires $config['boards'] and $config['categories'] to be set."

I need to install Categories theme, how can I do it?
Where can I find this configuration and what should I do?

Could you spare me a moment please, I am a green hand in this.

**Comment by savetheinternet** [comment]
Use the support board for things which aren't bugs.

**Comment by azat-io** [comment]
Support board did not help me with this issue.

Can you tell me where can I find this category please?
