### ISSUE TITLE
208.54.39.0 IP range has a special condition.

### ISSUE THREAD

**Issue by seisatsu** [savetheinternet/Tinyboard#17]
It is unacceptable to add conditions in the source code for certain IP blocks. This is really sloppy and could cause problems.

The 208.54.0.0 IP block belongs to T-Mobile USA. Please find another way to do what you're doing.

**Comment by savetheinternet** [comment]
I completely understand and agree with you.

I wasn't aware that I committed this, sorry. It was supposed to be a "quick fix" so I could later locate a bug.

I did remove this earlier this week, in commit 5be1a8d8edd411dcd1722383491e74def28b7536.
