### ISSUE TITLE
Send secure cookie

### ISSUE THREAD

**Issue by jdh8** [savetheinternet/Tinyboard#177]
I suggest setting secure cookie if a mod logs in via HTTPS.
https://github.com/jdh8/boards/commit/d819fc498d47c1ca346f3d60d1f2a5b24c79ce35

On [my site](http://boards.jdh8.org), mod.php is redirected to HTTPS.  Would my patch cause problems on an HTTP/HTTPS dual moderation site?

**Comment by czaks** [comment]
I believe that no issues would arise, other than having to log in twice.

Another thing is that sessions are tied to IP addresses, but better
security is better.

I would also consider setting httpOnly
5 cze 2014 16:09 "Chen-Pang He" notifications@github.com napisał(a):

**Comment by jdh8** [comment]
HttpOnly is already set on Tinyboard.

By the way, thanks for your imageboard solution. It outperforms old crappy ones.

**Comment by jdh8** [comment]
This patch has been committed into [vichan](https://github.com/vichan-devel/vichan).
https://github.com/vichan-devel/vichan/commit/6716a24b6844ab2ec1ee7588f1cf024070c395ed
