### ISSUE TITLE
Ban List bug

### ISSUE THREAD

**Issue by seisatsu** [savetheinternet/Tinyboard#19]
If you make a ban, and then make a second, longer ban on the same IP while the first is still active, after the first ban expires, only the first ban will show up (crossed out) in the ban list. Also, while both the bans are active, they will both show up in the ban history for that IP, but only the first shows in the ban list.

**Comment by savetheinternet** [comment]
This is more of a design flaw rather than a bug.

**Comment by savetheinternet** [comment]
To elaborate, bans are grouped by IP address in the list. Multiple bans for one address won't show.

For some reason this was a necessity prior to 0.9. Fixing now.
