### ISSUE TITLE
User IP

### ISSUE THREAD

**Issue by rotenbaron** [savetheinternet/Tinyboard#200]
rDNS($ip) return all IP-addresses like 127.0.0.1
Cannot find the source of this problem.

**Comment by goosehub** [comment]
I'm not familiar with that function. What behavior are you expecting and how do you know it's not giving you it's intended behavior?

**Comment by rotenbaron** [comment]
Well, I believe that function should take IP-address from user hostname (as far as I understand those php-sources), but for now all ip-addresses it's create are 127.0.0.1

![2016-01-14_17-12-47](https://cloud.githubusercontent.com/assets/600055/12326556/9c9e6b5c-bae2-11e5-859e-50e51d3b2c01.png)

**Comment by rotenbaron** [comment]
pages.php:788

```
if ($config['mod']['dns_lookup'])
    $args['hostname'] = rDNS($ip);
```

**Comment by goosehub** [comment]
Is this on your localhost, or on a live site with users?

**Comment by rotenbaron** [comment]
live site of course

**Comment by goosehub** [comment]
Unsure. I wish you luck finding a solution. Wish I could be of more help.

**Comment by kpcyrd** [comment]
Can you post details about your setup? You might be recording the IP of your reverse proxy.

**Comment by rotenbaron** [comment]
Yes, your reply totally gave me the idea. Turned out nginx on my server somehow became frozen and haven't received the new config. 

Thank you for help!
