### ISSUE TITLE
no images option on stylesheet

### ISSUE THREAD

**Issue by ghost** [savetheinternet/Tinyboard#207]
the wierd man boys at wizchan.org have a "No Images" selection in the stylesheets. Can someone tell me how i can add that to my board??

**Comment by seisatsu** [comment]
Why don't you look at their stylesheet? Also Tinyboard is a dead project; you should check out the Vichan fork.

**Comment by ghost** [comment]
the stylesheet directory does not allow ppl to see what is in there
