### ISSUE TITLE
Weird template bug removing </script>

### ISSUE THREAD

**Issue by savetheinternet** [savetheinternet/Tinyboard#28]
`<script type="text/javascript">rememberStuff();</script>`

...turns into:

`<script type="text/javascript">rememberStuff();`.

The `</script>` tag is for some unknown reason omitted.

<b>Solution</b>: Move away from current horrible template system.

**Comment by savetheinternet** [comment]
Because fixing this bug means a huge change, it will remain in the 0.9.3 release.

**Comment by Circlepuller** [comment]
Might I recommend Twig as a replacement?

**Comment by savetheinternet** [comment]
Moved to Twig; problem is solved.

**Comment by savetheinternet** [comment]
This was never actually a bug in Tinyboard. Further investigation reveals that it was actually a Chromium bug, the web browser I was using to view page source.
