### ISSUE TITLE
Twig cache overrides template file changes.

### ISSUE THREAD

**Issue by seisatsu** [savetheinternet/Tinyboard#29]
Files with templates in the templates/ directory appear to be rebuilt from the Twig cache of the template rather than the actual template. Changing a template in templates/ and then rebuilding the static files will rebuild with the cached version of the template.

In addition there doesn't appear to be any way to clear the Twig cache, and it doesn't appear to update itself under any circumstances. Recommend that it be disabled, or set to refresh when the static files are rebuilt in the mod panel.

**Comment by savetheinternet** [comment]
As Twig cache can significantly speed things up, I think we should go with the latter suggestion.

**Comment by savetheinternet** [comment]
Twig_Environment::clearCacheFiles() exists in Twig.
