### ISSUE TITLE
Creator has crippling autism

### ISSUE THREAD

**Issue by cornellhub** [savetheinternet/Tinyboard#33]
Attempts to sue users under nonexisting grounds, has crippling autism that hinders development, stalks users, stalks family and friends of users, should be arrested on multiple counts. 

Creator should recuse himself from the project as he is the single largest obstacle to progress.

**Comment by savetheinternet** [comment]
Honestly, when I first read the title of this issue I actually thought it would be legitimate. But it wasn't. This is not a Tinyboard issue at all; don't be fooled.

You know, by posting this nonsense "issue" you've wasted my valuable time, effort and resources (internet bandwidth and processing power). That time, effort, bandwidth and processing power could have been put to a more productive task and created a profit, so I will be demanding full compensation for that.

You can't hide from the law forever. You are getting sued and there is absolutely nothing you can do about it. See you in court.

**Comment by stal888** [comment]
lol

**Comment by emmausrs** [comment]
I fully agree. Every day, STI threatens to sue me for $100,000/day, and he constantly insults me, calling me things like "psychotic fucktard" and "fucking idiot". In fact, I'm considering switching to better software such as Yotsubanome or Kusaba X solely because of his behaviour.

**Comment by itsachen** [comment]
lol

**Comment by fuki98** [comment]
LOL
