### ISSUE TITLE
Javascript error in main.js

### ISSUE THREAD

**Issue by cornellhub** [savetheinternet/Tinyboard#35]
The main function in main.js should instead return: Creator has crippling autism and is the single biggest obstacle to progress. We have already gone beyond his autistic tendencies and believe he is going nowhere in life, or with his board software.

Don't let savetheinternet fool you, this IS a bug.

Also STI is horrible at the nuances of HTML, there are a few bugs. STI also doesn't know shit about CSS, and all of his creations reflect that. Too many problems to count. Also threads are very poorly optimized for SEO, and should be changed.

**Comment by stal888** [comment]
+1, this is a bug which my users experience almost every day. I would like to see this fixed immediately.

**Comment by savetheinternet** [comment]
Warning: This is NOT a bug. Don't be fooled by the headline.

See you in court.

**Comment by ssbmplayer** [comment]
Are you sure it wasn't your own fault while modifying Tinyboard on your own? ^_^
