### ISSUE TITLE
from Russia with issues

### ISSUE THREAD

**Issue by Gimme-zz** [savetheinternet/Tinyboard#38]
Hi, I really liked tinyboard, but I have a few questions
1) how to change the language of imageboard?
I tried to change the line $ config ['locale'] = 'ru_RU'; in the config.php file and instance-config.php, but it only works on the local server and does not work on hosting.
2) if you try to write in the "Comment" Russian characters, it displays an error "The body was too short or empty."
English characters are displayed correctly
I think you understand what I wrote above, I hope that these errors will be corrected soon. thanks in advance
//google translator

**Comment by savetheinternet** [comment]
Thanks for taking an interest in Tinyboard. I will try to address your points to the best of my ability.

> 1) how to change the language of imageboard?
> I tried to change the line $ config ['locale'] = 'ru_RU'; in the config.php file and instance-config.php, but it only works on the local server and does not work on hosting.

For the Russian translation to work, you'll need to install RU locale data files on the server. You might also need to install gettext  (php-gettext). Assuming you use an OS based on Debian (as you should), `sudo apt-get install locales php-gettext` should do the trick. If you use a shared web host, you obviously won't be able to install these packages yourself, but you can try asking your host for help.

I should note that the current Russian translation in Tinyboard is largely incomplete. The Russian translation was submitted during the very beginning of internationalization support.

> 2) if you try to write in the "Comment" Russian characters, it displays an error "The body was too short or empty."

That's weird. Tinyboard is meant to be able to multibyte characters. I haven't been able to reproduce this error: http://i.imgur.com/jSsy4.png. What version of Tinyboard do you use? What version of PHP? And what HTTPd do you use?

**Comment by Gimme-zz** [comment]
All done, the problem was hosting, I moved to another tinyboard shared hosting and it worked.
Another issue, buttons do not work captcha, when I click on them they are simply text. The picture below
http://i.imgur.com/MJrwx.png
my English is impossible to understand :D
//google translator

**Comment by savetheinternet** [comment]
Sorry, I can't quite understand what the problem is. Is it any different to http://i.imgur.com/ouXJT.png? Are you referring to the "Get a new challenge" and "Get an audio challenge" buttons? If you are, I'm not really sure why it's like that. Tinyboard shouldn't affect that -- we use Google's reCAPTCHA API the standard way.

Are you able to provide me with a link to your website? It could help.

Also, you shouldn't really need to enable reCAPTCHA straight away, unless you're under some sort of attack. Tinyboard has much better flood/spam preventions than other imageboard engines.
