### ISSUE TITLE
Maximum image size

### ISSUE THREAD

**Issue by pmer** [savetheinternet/Tinyboard#4]
**ISSUE**

Unnecessarily large images could use inconvenient amounts of RAM, CPU cycles, and bandwidth.

**REPRODUCTION**

Upload a 10 MB image to Tinyboard. It will require 10 MB of bandwidth every time it is viewed.

Uploading http://omegadev.org/~pmerrill/white16.png will require 500 MB of free RAM on the server to process.

**EXPECTED RESULT**

Any of:
- The post is refused, and the user is notified of what size image is acceptable.
- The full image is automatically reduced down to a convenient size. (Would only solve bandwidth problem, not CPU or RAM.)

**Comment by savetheinternet** [comment]
Maximum filesize has been added in commit 690f206a63967805c1d61806683947ac6f2a2175.

I think we should also add a maximum for the image dimensions.

**Comment by savetheinternet** [comment]
Done in commit 8849f5a2db1d041df556d069bb0b530aee11294e.
