### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by captainspazz** [savetheinternet/Tinyboard#40]
both on 0.9.4 and 0.9.5 I get this while trying to install:

Parse error: syntax error, unexpected '&', expecting T_VARIABLE or '$' in /usr/local/pem/vhosts/284875/webspace/httpdocs/chan/install.php on line 35

**Comment by savetheinternet** [comment]
What version of PHP are you using?

**Comment by captainspazz** [comment]
You are right in assuming it's php version related. I have 4.4.9

I have been struggling with getting 5 for many hours. I have  contacted the hosting's technical support. Thanks for the prompt reply.

**Comment by savetheinternet** [comment]
PHP 4 is ancient.

I'm glad I could help.
