### ISSUE TITLE
$config['mod']['flood'] = JANITOR; not working

### ISSUE THREAD

**Issue by captainspazz** [savetheinternet/Tinyboard#42]
I wanted my janitors to have zero delay between posts so I set 

$config['mod']['flood'] = JANITOR;

that did the trick, the only problem is that it seemed to apply to normal users as well not just JANITORS so now the flood detection became pretty much useless.

**Comment by savetheinternet** [comment]
Hi,

This should have been fixed in 75efb21035ecf3236edaa39ac8f357b7393f7250. I noticed this problem earlier.

Thanks.
