### ISSUE TITLE
Editing posts with HTML texts not working

### ISSUE THREAD

**Issue by captainspazz** [savetheinternet/Tinyboard#44]
I know the editing of posts is in beta so I can't expect it to be fully functional. I also don't know if this is a known bug or not however I have been using the post editing function and it seems to work quite well.

Unless I am editing post with HTML text in which case it gets saved as plain text.

**Comment by savetheinternet** [comment]
Thanks.

The post editing feature is very new. I will add this functionality soon, along with the ability to edit subjects, names, etc.

**Comment by savetheinternet** [comment]
This has since been fixed with the new post editor.
