### ISSUE TITLE
Can't enable the 2 custom flood filter

### ISSUE THREAD

**Issue by captainspazz** [savetheinternet/Tinyboard#45]
I have been using 0.9.5
I upgraded to 0.9.6-dev4 and now when I enable the 2 custom flood filters in instance-config I get these errors when trying to post

Unknown filter condition: posts_in_past_x_minutes

Unknown filter condition: threads_with_no_replies_in_past_x_minutes

**Comment by savetheinternet** [comment]
[Config/Flood_filters](http://tinyboard.org/docs/?p=Config/Flood_filters)

The `posts_in_past_x_minutes` and `threads_with_no_replies_in_past_x_minutes` are currently unavailable in the latest git revision, following a major update to the filters system. It should be re-added within the next few days (or weeks). Sorry.

You could use the `custom` condition to do the same thing for the time-being.

**Comment by captainspazz** [comment]
Thanks for the reply. Glad to know it will be re-added.
