### ISSUE TITLE
Inline expanding not working in FF

### ISSUE THREAD

**Issue by captainspazz** [savetheinternet/Tinyboard#47]
chrome and IE have no problem with it but clicking a thumb in FF causes it to open in a new window

**Comment by savetheinternet** [comment]
Are you sure Javascript isn't disabled or something?

What Firefox version? It works for me.

**Comment by captainspazz** [comment]
FF aurora. I found different chans using TB 0.9.6 and it works there with FF but on my chan it doesn't.

I stopped embedding any additional JS files and it still didn't work. 

The problem is that the script doesn't get called for some reason.

If I open the scratchpad in FF (shift + f4) and write the function then run it again - it works. 

If I force launch the function using body onload then it also works.

**Comment by savetheinternet** [comment]
Well, in v0.9.6, `$config['inline_expanding']` was dropped and replaced with `$config['additional_javascript'][] = 'js/inline-expanding.js';`. Do you have that in your config file? Do you need to rebuild, maybe?

**Comment by captainspazz** [comment]
Yes, I  have that. Like I said it works in the other browsers but in FF aurora or nightly doesn't. I think it's something wrong with the way in handles the on load events. 

I also have a different problem that's probably related to the same thing. When I click a post number in the index page it will open up the thread (posting mode reply) and put the quoted post in the comments box (>>xxxx) but the site will still be loading (the loading icon is still spinning). Once the site finishes loading the comments box gets emptied. Once again it works in chrome and other browsers.

I'm not sure what the best way to debug this would be.Is there a way I can track JS more closely (what script is being run, when it is called and so on)?

**Comment by russelg** [comment]
captainspazz, try debug it with Firebug's web inspector.

**Comment by savetheinternet** [comment]
Doesn't Firefox have an inbuilt error console?

**Comment by russelg** [comment]
Oh it does.

Try CTRL+Shft+J.

**Comment by captainspazz** [comment]
I was thinking more in terms of tracking what JS functions are run step by step. I don't get any error when trying to expand the image. Like I said the problem is due to the the expanding script not being run since the page loading event doesn't seem to trigger.

If I enter in this in the console :
ready();

then the imagine expanding will work
but
it will also throw 'undefined' next.

**Comment by savetheinternet** [comment]
Sorry I haven't had a chance to test this for myself yet. Inline expanding works fine for me in Firefox 11.0 and a bunch of previous versions.

Is it just your Tinyboard instance that you're having this problem with? Have you tried inline expanding on [other Tinyboard sites](http://4chon.net)?

> it will also throw 'undefined' next.

Does it say the line number and the script filename where that's thrown?

> If I enter in this in the console :
> ready();
> then the imagine expanding will work

That's strange, because `<script type="text/javascript">ready();</script>` should be before `</body>` always. Can you confirm this? Maybe add a `console.log('test');` to the `onready()` function main.js to check if it's being called correctly.

**Comment by captainspazz** [comment]
I added the console log and yes, ready wasn't triggering (and it was indeed placed at the bottom of the html file). I added it to body onload and now it works. Does that cause any unwanted side effects (like some scripts being run more than they have to)?
