### ISSUE TITLE
IE 8 tab crash when posting via mod.php

### ISSUE THREAD

**Issue by NotAdam** [savetheinternet/Tinyboard#48]
Basically, any attempt I have made to post via mod.php crashes the tab in ie8. I can't disable javascript to see if it works then, as I only use IE when I'm at school.

**Comment by emmausrs** [comment]
Get a Mac.

**Comment by savetheinternet** [comment]
I think I've experienced this before, nearly a year ago.

Obviously this is an IE's fault and not Tinyboard's (no browser should ever "crash" because it can't handle a page). I will have a look at it anyway and try to find a workaround.
