### ISSUE TITLE
Table 'mydb.posts_' doesn't exist

### ISSUE THREAD

**Issue by captainspazz** [savetheinternet/Tinyboard#49]
I updated to 0.9.6-dev4. It works fine for the most part except when issuing a ban which throws this error

Table 'mydb.posts_' doesn't exist

when putting in a ban message.

**Comment by savetheinternet** [comment]
Switch to the [`mod-rewrite`](https://github.com/savetheinternet/Tinyboard/tree/mod-rewrite) if you don't use the web config editor or post editing.

`git checkout mod-rewrite`
