### ISSUE TITLE
Case-sensitive file extensions

### ISSUE THREAD

**Issue by savetheinternet** [savetheinternet/Tinyboard#5]
**ISSUE**

.JPG files get rejected when .jpg files are accepted.

**REPRODUCTION**

Upload an image with a .JPG extension to Tinyboard.

**EXPECTED RESULT**

The image should be handled as a JPEG.

**Comment by pmer** [comment]
Fixed in commit 1f1417373f7358b31f102072392c5c7a7a16f2e8
