### ISSUE TITLE
admin  rights issue

### ISSUE THREAD

**Issue by captainspazz** [savetheinternet/Tinyboard#50]
I gave my janitors the right to BAN users. However I don't want them to see the IPs of other users. That works fine and dandy UNTIL they get to ban a user in which case they can see everyone's IP.

Basically I want them to be able to ban the users but without seeing their actual IP (so pretty much making the "IP (or subnet)" textfield unavailable to them)

These are some of the settings I made.

$config['mod']['show_ip'] = MOD;
$config['mod']['ban'] = JANITOR;

**Comment by pmer** [comment]
Isn't this something Tinyboard already supports?

**Comment by savetheinternet** [comment]
This is possible with the latest version.

![](http://i.imgur.com/37SXA.png)
