### ISSUE TITLE
Can't embed Anonym.to code

### ISSUE THREAD

**Issue by notWYS** [savetheinternet/Tinyboard#51]
Hey.
I used to be able to embed anonym.to code just fine, by using this piece of code in in instance-config.php:
http://pastebin.com/nALT26HG
However, since i upgraded from v0.9.5 to v0.9.6-dev-4, i couldn't manage to make it work anymore.
Can you please help me solving this issue?
Thanks in advance

**Comment by emmausrs** [comment]
This is not an issue with Tinyboard.

**Comment by notWYS** [comment]
Well, since it used to work with v0.9.5, i guess something has changed and broken the embedding of code in the footer.
Or better, i can see the anonym.to code in the source of the pages, but it doesn't work.
