### ISSUE TITLE
Is Tinyboard fully GPL-compatible?

### ISSUE THREAD

**Issue by Rox64** [savetheinternet/Tinyboard#53]
Hi, I have discovered this project and I want to play a little with it. But I have checked the license, and I'm not sure if it's fully compatible with the GPL and if it can be relicensed under the GPL. The original license was like the X11/MIT license (so, as far as I know you can do whatever you want with it), but the new license since Nov 13, 2011 includes this condition:

"All copyright notices and permission notices (including this file) shall be included and remain unedited in all copies or substantial portions of the Software. This explicitly includes but is not limited to the Tinyboard copyright notices found in the footers of some template files."

I think this means I can use some code from Tinyboard on GPL projects but I cannot change the license and relicense it under the GPL and that the Tinyboard license itself is now copyrighted, right?

**Comment by emmausrs** [comment]
I don't see how GPL incompatability is an issue.

**Comment by pmer** [comment]
That sounds correct. You cannot relicense code unless you get permission from the owner. However, you should be able to use an MIT licensed project within a GPL project without problem. Further, you may license any changes you make to this project under any license you want.

This issue can probably be closed.
