### ISSUE TITLE
quick-reply.js causes "You look like a bot." error

### ISSUE THREAD

**Issue by ghost** [savetheinternet/Tinyboard#59]
Normal reply works perfectly but when using quick reply, I always get held for a bot. My guess is that the script creates a new input field which isn't allowed by /inc/config.php, but I'm not sure.

**Comment by ghost** [comment]
I just found the 'quick-reply' value is added on the config.php version here - my bad

**Comment by ghost** [comment]
Gah.. Sorry to reopen this but it seems I jumped the gun. It's still not working.

**Comment by fourfivesix** [comment]
I can confirm that this bug still happens. I've found its cause:

The check that causes this error is in `post.php` in line `168`:

```
        if (!(($post['op'] && $_POST['post'] == $config['button_newtopic']) ||
            (!$post['op'] && $_POST['post'] == $config['button_reply'])))
                error($config['error']['bot']);
```

Whenever you click on the Quick Reply button, `quick-reply.js` sets $_POST['post'] to 'New Reply', but if your $config['button_reply'] has been changed to something else (maybe translated), then the check above won't pass and the user will be wrongly considered a bot.
