### ISSUE TITLE
Error: Unknown column 'uri' in 'order clause' (Installation Issue)

### ISSUE THREAD

**Issue by kete21** [savetheinternet/Tinyboard#60]
I don't know if this belongs here, but I honestly don't know what this means. I put my google-fu to work and it seems to be some sort of mysql error but I'm still very hazy. Help very much appreciated.

**Comment by savetheinternet** [comment]
Try the `mod-rewrite` branch. I'm going to fix a few bugs today and hopefully get v0.9.6 done soon.

**Comment by 3cbb53c73415ba373448c11dacc69b05** [comment]
help me, same problem

**Comment by seisatsu** [comment]
This is a dead project. Use [Vichan](https://github.com/vichan-devel/vichan) instead which is the most recently maintained fork of Tinyboard.
