### ISSUE TITLE
expand.js and doesn't allow image expanding

### ISSUE THREAD

**Issue by ghost** [savetheinternet/Tinyboard#61]
When you click on an image in an expanded thread, you will be redirected to a new tab, even if you have inline expanding enabled (with or without using inline-expanding.js).

**Comment by czaks** [comment]
This commit fixes the issue:
https://github.com/vichan-devel/Tinyboard/commit/1d76164e291a6f73378e33fa1f70f804acad0838

The downside is that image expanding now needs jquery, so the files need to be rearranged in config to include jquery first.

I can try to rebase it to the current upstream if needed.
