### ISSUE TITLE
Unhanded error before install(database.php)

### ISSUE THREAD

**Issue by ghost** [savetheinternet/Tinyboard#63]
Unhanded error before install:
must be fixed.

Warning: PDO::__construct() [pdo.--construct]: [2002] No connection could be made because the target machine actively refused it. (trying to connect via tcp://localhost:3306) in C:\WWW\index\Tinyboard\inc\database.php on line 52

**Comment by savetheinternet** [comment]
That is a problem with your MySQL server, but I need to add error handling.

There are a few typos in your title.

**Comment by savetheinternet** [comment]
Should be fixed in 28392a12d39a2d94f7c39adabf3c108c790ec01a.
