### ISSUE TITLE
Post loses ban message when one of its post links goes stale

### ISSUE THREAD

**Issue by MacilPrime** [savetheinternet/Tinyboard#66]
When a regular post has links to other posts, and one of those posts are deleted, and the track_cites option is on, then the post body gets recreated from the body_nomarkup field, losing any changes made to the body field, such as a ban message. (Think this also happens to posts in a thread that is moved between boards.)

This is also an issue for me as I have several functions in my config files that run on the post event which modify the a post's body (but not body_nomarkup), and there isn't any event that runs whenever the body field is regenerated from the body_nomarkup field. I think that would be a very useful event; it could run after a post is first made, moved to another board, or edited too.

**Comment by MacilPrime** [comment]
Thought about this for a while, and I think I've come up with a good solution that solves some other issues too.

A new column would be added to the posts_\* tables, called body_modifiers. It would be a TEXT field like body and body_nomarkup. It would contain an associative array (serialized into a string into the database some arbitrary way like JSON, which looks like PHP handles easily) that's used to control the rendering of the post ("render" referring to creating the body value from the body_nomarkup value; guess "build" would work too).

When a post is made as a raw post for example, then {raw: true} would be set in body_modifiers. Then the post body is rendered, and the code sees that raw is true, so populates body with the same value as body_nomarkup instead of applying markup. Then the 'post-render' event is called on the post, giving any events a chance to look at the body_modifiers and take some action on the post body.

When a ban message is appended to a post, then {banmessage: "USER WAS BANNED FOR THIS ETC ETC"} would be added into the post's body_modifiers, and then the post would be re-rendered. Depending on whether or not raw was set and set to true, the body value would be set to body_nomarkup with or without markup applied, and then the 'post-render' event would get called. A 'post-render' event function built-in to Tinyboard would check whether the banmessage value was set in body_modifiers, and then append the value of that to the post body if so.

A post would be rendered (with the post-render event getting called) when it's made, when it's edited, when a post link it references dies, or when it's moved to another board. This would fix the bugs where raw posts lose their rawness when being moved, and the tendency of ban messages to disappear (such as when being moved). The site I run and many other imageboards often have a board that good threads are moved to for future viewing, and a board where subpar threads are moved to die, and it's kind of disappointing to have the posts get affected in the process.

---

I've also been a fan of setting up short-lived silly config events that affect posts. Sometimes I'll add filters / word replacements / new markup to specific users, such as to disrupt a disruptive user, or to give a lucky user some special markup ability for a silly thread. I've done this before by adding a 'post' event function which just changed the post body, but re-rendering the post (such as when the thread got moved later) undid the event's actions. With body_modifiers, then I could have a 'post-render' event which checks for the no_caps value in the body_modifiers and sets the post body to be all lower case, and then for a while I'd have a 'post-early' event which checks for the target user's tripcode or IP and adds the no_caps modifier to new posts by them. Then I can remove the 'post-early' event later when I deem that user has rights to capital letters again, but as long as I keep the 'post-render' event around, then if I move the user's no_caps posts they'll continue to be in lower case. ('post-early' events would run only when a post is first made, before it's rendered. 'post' events would stay as how they worked before, running after the body field is populated.)

Another use case of mine is for dice rolling: I've got a 'post' event that for example replaces [2d6] in a post with `<span class="diceroll">Roll 2d6 = 9</span>`, not always resulting in 9 of course. Currently, if the post is re-rendered, then it reverts back to just [2d6]. With a 'post-render' event but no body_modifiers value, I could re-roll the dice and get a new value, which is no good. I could make the dice roll a deterministic function based on the post number (and secret salt values), but then if it's moved to a different board (with a new post number) then the roll result changes. With body_modifiers, then I could move the dice roll function into the 'post-render' event, have it check for a diceroll_seed value in the body_modifiers (if there isn't one, then calculate a seed and set it into the body_modifiers) and then use that as the seed to the deterministic rolling function.

I think I'll code this up (body_modifiers field and adding the new events) sometime. Anyone have any thoughts? This latter lower section is probably pretty specific to me, but I think the generic benefits I described in the top part would be valuable on their own too.

**Comment by MacilPrime** [comment]
Alternatively, Tinyboard could be changed to avoid ever re-rendering the post body from body_nomarkup, and instead when a post is moved to another board, post numbers in links are changed directly in the rendered HTML in the post body, and when a post is deleted, all the posts reference it have only the post body directly modified again.

The metadata route isn't all that complex, nearly all of my post above was just showing some of its use cases, but this solution would be a bit simpler and cover the default Tinyboard use cases well. Being able to keep some extra metadata with posts seems like it could be useful for custom user event stuff, but it's a bit less necessary this way. I'm undecided which solution I like more.

**Comment by savetheinternet** [comment]
I very much like the `body_modifiers` solution and I have nothing to add to your idea.  It would definitely solve a lot of the problems Tinyboard currently faces, as well as add new opportunities for general awesome-ness. Thank you for going into so much detail.

I think directly modifying the rendered HTML could prove to be a difficult task. This would require actually parsing the HTML code, which I would rather avoid (even if it's just by a regular expression). Also, I don't think it would work with post editing.
