### ISSUE TITLE
Support for more than one board at a time

### ISSUE THREAD

**Issue by pmer** [savetheinternet/Tinyboard#7]

**Comment by savetheinternet** [comment]
This will be done after it's stable with just one.

**Comment by savetheinternet** [comment]
Check out the [multi-board](https://github.com/savetheinternet/Tinyboard/tree/multi-board) branch. Will be merged into the master once ready. It's relatively stable at the moment.

**Comment by pmer** [comment]
Added in commit 8809b2e50e2c0bb725aeb09d82f6c352e3110332
