### ISSUE TITLE
Error in PDO::unbuffered query - on install

### ISSUE THREAD

**Issue by ghost** [savetheinternet/Tinyboard#75]
**Message:**
Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.

http://domain/install.php?step=4

**Comment by savetheinternet** [comment]
Did you always get this error? Have you made any changes to your setup recently that might have caused this?

**Comment by ghost** [comment]
Yes, when I attempting to install.
Also i dont any change to the setup.

**Comment by Juribiyan** [comment]
I still get this error on install
