### ISSUE TITLE
mod.php?/Rebuild title is "ebuild"

### ISSUE THREAD

**Issue by komugifb** [savetheinternet/Tinyboard#79]
http://yoursite.com/mod.php?/rebuild has a <title> tag with "ebuild".
This is incredibly minor, but my OCD triggered and I felt need to post it here.

**Comment by komugifb** [comment]
Seriously, html enabled in here?
"<"title">" tag is ebuild and not rebuild.

Yeah, I have ocd

**Comment by seisatsu** [comment]
I'm not seeing this.

**Comment by komugifb** [comment]
It dissapeared, no idea why.

"Michael D. Reiley" notifications@github.com wrote:

> I'm not seeing this.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/savetheinternet/Tinyboard/issues/79#issuecomment-8914313

## 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.
