### ISSUE TITLE
Unicode characters shorten maximum length in inputs

### ISSUE THREAD

**Issue by savetheinternet** [savetheinternet/Tinyboard#8]

**Comment by pmer** [comment]
The Unicode character ★ does not actually take up three characters. It takes up three bytes. A UTF-8 character can be anywhere between 1 to 4 bytes in length.

Somewhere in our code we must be doing a byte-length comparison when we should be doing a character-length comparison.

**Comment by pmer** [comment]
We need to do two things:
- Expand our database columns to 4 times their current width to support multibyte characters.
- Call mb_internal_encoding("UTF-8") and then replace a few strlen() calls with mb_strlen() wherever we want to be Unicode-conscious.
