### ISSUE TITLE
Inline-expanding only working on indexes, not in threads

### ISSUE THREAD

**Issue by komugifb** [savetheinternet/Tinyboard#83]
This might be a specific problem just for me, but my inline-expansion script only seems to work properly when I am on the index pages looking at the overview of threads. When I enter any thread the inline-expansion stops working and all images go to a new tab.
What could cause this? I have looked through my thread.html and github's thread.html and see no significant changes (Some changes, but only small ones such as Replacing "No." with a bold japanese version of "#").

My thread.html:
http://pastebay.net/1157656

**Comment by komugifb** [comment]
Index.html: Console returns no errors.
Thread.html: TypeError: Cannot read property 'src' of undefined

Apparantly line 17 on inline-expanding.js returns an error on the thread page, but not index page.
I do not understand much of this though.

**Comment by savetheinternet** [comment]
Do you have any other scripts enabled? Have you made any changes to the HTML or JS?

**Comment by komugifb** [comment]
I have, but I don't understand how this should change that much, I've only
added a return button, and top+bottom buttons. Also edited small things
such as No. 123 to # 123.
Is this not allowed? What can I change, what cant i change? Please notice I
did edit the index file, but and the thread. and the scripts run properly
in the index, so they SHOULD be the same if my logic is correct since i
haven't done anything diffrent on index than on thread. pls excuse sloppy
answer, im in the middle of an exam. Yay, can't go yet..

2012/11/25 Michael notifications@github.com
