### ISSUE TITLE
Replies omitted showing wrong values

### ISSUE THREAD

**Issue by captainspazz** [savetheinternet/Tinyboard#84]
Hi. I've seen this happen multiple times on my chan. The "X replies ommited" post on the index pages shows a wrong number. For example now i have a thread with 20 replies (each with an image) and on the index page I get
16 posts and 16 image replies omitted

**Comment by savetheinternet** [comment]
I'm not experiencing this issue.

Are you still getting it with the latest revision?

**Comment by captainspazz** [comment]
nvm. I'm an idiot. Close the issue pls.

**Comment by kekkj** [comment]
PM'D U A FIX ;)
HERE'S A LINK TO A FIX [megaupload link]
HERE'S A LINK TO A FIX [YOU MUST SIGN IN TO VIEW LINKS]
NVM FIXED IT
