### ISSUE TITLE
reCaptcha strange behavior (in Firefox)

### ISSUE THREAD

**Issue by ghost** [savetheinternet/Tinyboard#85]
It only seems to be doing it in Firefox with my install (where the reCaptcha side-buttons do nothing).  A work around to regain the reload captcha functionality that I implemented (for anyone who had the same problem) was to hardcode the reload() code to a link and then place it above the captcha and hide the buttons altogether:

style.css:
`img#recaptcha_reload,img#recaptcha_switch_audio,img#recaptcha_whatsthis {
 display: none; 
}`

main.js:
`$('.reloadCaptcha').live("click",function(){
Recaptcha.reload();
});`

post_form.html
`<a class="reloadCaptcha">New captcha?</a>`

**Comment by savetheinternet** [comment]
This should be fixed in 5bf0e7f7e76cd3610e0aa692e0c433aca594ee51.
