### ISSUE TITLE
Can't find install.php on the net

### ISSUE THREAD

**Issue by jollymx** [savetheinternet/Tinyboard#86]
Hello everyone,

I uploaded the Tinyboard files through ftp. The problem is that I cant find the install.php prompts on the internet. My domain is http://www.cartoonchan.com Also, I deleted the files that were already on the ftp without me uploading anything. How do I fix this? Do you have a link for the prompts? Thanks.

**Comment by savetheinternet** [comment]
Not really sure what you mean. You browse to the install.php file that you uploaded.

It comes with Tinyboard.
