### ISSUE TITLE
Hyphens being transformed into dashes incorrectly

### ISSUE THREAD

**Issue by RogerDodger** [savetheinternet/Tinyboard#88]
[inc/functions.php, line 1364](https://github.com/savetheinternet/Tinyboard/blob/30ecfc76e7bc2ba5f1b830f60234f60d902a18df/inc/functions.php#L1364)

The comments are correct, but the code is wrong. Three hyphens should turn into `&mdash;` and two hyphens into `&ndash;`.

**Comment by savetheinternet** [comment]
Sorry for taking so long to fix this trivial issue.

**Comment by RogerDodger** [comment]
The en dash substitution occurs before the em dash one, so it's still not quite working. Three hyphens turn into `&ndash;-` rather than the intended `&mdash;`.
