### ISSUE TITLE
Redrawing images causes GIF animations to disappear

### ISSUE THREAD

**Issue by savetheinternet** [savetheinternet/Tinyboard#9]
The redrawing of images to remove excess un-wanted and possibly malicious data which was added in commit bb1abb85e1dd089497b6a852c5b95e89c211b6d8 breaks animated GIFs by stripping the animation, leaving only the first frame.

After researching, this may be hard to overcome. We cannot fix this with PHP's GD libraries. If we read the technical specifications of the Graphics Interchange Format and created a method to find the end of the GIF image and strip the excess, we could fix this.

A new commit is coming that will allow you to turn off redrawing for GIF images. Hopefully it is temporary.
EDIT: Commit: 1e201212242c758a4d797711388aa566542224f4.

**Comment by seisatsu** [comment]
You can get around this by adding ImageMagick support. Please do so.

**Comment by savetheinternet** [comment]
> You can get around this by adding ImageMagick support. Please do so.

Okay. Soon.

**Comment by savetheinternet** [comment]
ImageMagick support is added. I should create a config option to allow animated thumbnails.

**Comment by savetheinternet** [comment]
Actually, this bug is no longer valid because that "redrawing" feature was basically removed a while ago.

I was confused and thought it was for animated thumbnails.

**Comment by czaks** [comment]
imagemagick also doesn't do it's best with gifs, at vichan we were using gifsickle. actually, imagemagick is a really powerful project, i know there are some switches for optimizing gifs (that even save CPU power).

**Comment by pmer** [comment]
Can this issue be closed?

**Comment by savetheinternet** [comment]
Probably.
