### ISSUE TITLE
Search absent from mod panel

### ISSUE THREAD

**Issue by komugifb** [savetheinternet/Tinyboard#98]
Editing posts results in a 404, saying edit_post or whatever doesn't exist, this also happens when I attempt to search for posts.

**Comment by captainspazz** [comment]
Same here. granted it used to work at first But I reinstalled tinyboard and I think that's when it broke.

**Comment by Circlepuller** [comment]
Post editing page shouldn't 404 now, but the search function seems to be incomplete as of now.

**Comment by savetheinternet** [comment]
Updated the title of this bug to make it more accurate.

I just haven't gotten around to redoing the search stuff in Tinyboard since introducing the new mod panel code.

**Comment by savetheinternet** [comment]
Search is being reintroduced.

At the moment, you may search bans, IP address notes and moderation logs, but not posts.
